name: 'Does PR has at least one of the labels?'
description: 'Returns true or false depending on whether the PR has the specified label'
inputs:
  labels:  
    description: 'Comma separated list of labels'
    required: true
outputs:
  has-label: 
    description: 'Has the label?'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'check'  
  color: 'blue'